version = 0.1
[default.deploy.parameters]
stack_name = "EventsAlert"
resolve_s3 = true
s3_prefix = "EventsAlert"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CloudTrailName=\"management-events\" S3BucketName=\"2cloud-io-aws-cloud-trails-logs-786\" SlackWebhookUrl=\"https://hooks.slack.com/services/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\" EventPattern=\"{\\\"source\\\": [\\\"aws.iam\\\"]}\""
image_repositories = []
